[package]
name = "eren"
authors = ["BASED"]
license = "GPL-3.0"
version = "0.2.0"
edition = "2021"
description = "Stream & Download Cartoons & Animes"
keywords = ["anime", "allanime", "gogoanime", "scraper", "cli"]
repository = "https://github.com/Based-Programmer/eren"

[dependencies]
tokio = { version = "1.34.0", features = ["full"] }
isahc = "1.7.2"
url = "2.5.0"
serde_json = "1.0.108"
hex = "0.4.3"
skim = "0.10.4"
regex = "1.10.2"
once_cell = "1.18.0"

[profile.release]
strip = true
lto = true
codegen-units = 1
