[package]
name = "eren"
authors = ["BASED"]
license = "GPL-3.0"
version = "0.1.4"
edition = "2021"
description = "Stream & Download Cartoons & Animes"
keywords = ["anime", "command-line", "scraper", "webscraper", "cli"]
repository = "https://github.com/Based-Programmer/eren"

[dependencies]
tokio = { version = "1.29.1", features = ["full"] }
isahc = "1.7.2"
url = "2.4.0"
#serde = { version = "1.0.178", features = ["derive"] }
serde_json = "1.0.103"
hex = "0.4.3"
skim = "0.10.4"
regex = "1.9.1"
once_cell = "1.18.0"
