[package]
name = "eren"
authors = ["BASED"]
license = "GPL-3.0"
version = "0.2.2"
edition = "2021"
description = "Stream & Download Cartoons & Animes"
keywords = ["anime", "allanime", "gogoanime", "cli", "scraper"]
repository = "https://github.com/Based-Programmer/eren"

[dependencies]
tokio = { version = "1.35.1", features = ["full"] }
clap = "3.2.25"
isahc = { version = "1.7.2", features = ["json"] }
url = "2.5.0"
serde_json = "1.0.113"
hex = "0.4.3"
skim = "0.10.4"
regex = "1.10.3"
once_cell = "1.19.0"

[profile.release]
strip = true
lto = true
codegen-units = 1
